
# SEO settings
title: Jonathan from Growth
description: "Jonathan Pepin's notes about dev, growth and books."
keywords: ""
url: "http://www.jonathanfromgrowth.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-90129732-1
repo: http://github.com/jauny/jauny.github.io
twitter_username: "jauny"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Jonathan Pepin"
  job      : "Software Engineer"
  bio      : "I focus on growth and great UX."
  thumb    : /images/author.jpg
  email    : jypepin@gmail.com
  url      : http://jauny.github.io
  github   : http://github.com/jauny
  twitter  : http://twitter.com/jauny
  facebook : https://www.facebook.com/jypepin
  linkedin : http://linkedin.com/in/jypepin

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@Jauny"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : lol
    title: lolz

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
